//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinPhone.Mail.Gmail.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinPhone.Mail.Gmail.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to archive.
        /// </summary>
        public static string ArchiveButtonText {
            get {
                return ResourceManager.GetString("ArchiveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attach.
        /// </summary>
        public static string AttachButtonText {
            get {
                return ResourceManager.GetString("AttachButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to speak.
        /// </summary>
        public static string DictateButtonText {
            get {
                return ResourceManager.GetString("DictateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to discard.
        /// </summary>
        public static string DiscardButtonText {
            get {
                return ResourceManager.GetString("DiscardButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done.
        /// </summary>
        public static string DoneButtonText {
            get {
                return ResourceManager.GetString("DoneButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forward.
        /// </summary>
        public static string ForwardButtonText {
            get {
                return ResourceManager.GetString("ForwardButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to label.
        /// </summary>
        public static string LabelItemText {
            get {
                return ResourceManager.GetString("LabelItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to labels.
        /// </summary>
        public static string LabelsButtonText {
            get {
                return ResourceManager.GetString("LabelsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to label settings.
        /// </summary>
        public static string LabelSettingsText {
            get {
                return ResourceManager.GetString("LabelSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mark as read.
        /// </summary>
        public static string MarkAsReadText {
            get {
                return ResourceManager.GetString("MarkAsReadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mark unread.
        /// </summary>
        public static string MarkUnreadText {
            get {
                return ResourceManager.GetString("MarkUnreadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new.
        /// </summary>
        public static string NewButtonText {
            get {
                return ResourceManager.GetString("NewButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove.
        /// </summary>
        public static string RemoveButtonText {
            get {
                return ResourceManager.GetString("RemoveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reply all.
        /// </summary>
        public static string ReplyAllButtonText {
            get {
                return ResourceManager.GetString("ReplyAllButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reply.
        /// </summary>
        public static string ReplyButtonText {
            get {
                return ResourceManager.GetString("ReplyButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string SaveButtonText {
            get {
                return ResourceManager.GetString("SaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send.
        /// </summary>
        public static string SendButtonText {
            get {
                return ResourceManager.GetString("SendButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsButtonText {
            get {
                return ResourceManager.GetString("SettingsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spam.
        /// </summary>
        public static string SpamButtonText {
            get {
                return ResourceManager.GetString("SpamButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sync.
        /// </summary>
        public static string SyncButtonText {
            get {
                return ResourceManager.GetString("SyncButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trash.
        /// </summary>
        public static string TrashButtonText {
            get {
                return ResourceManager.GetString("TrashButtonText", resourceCulture);
            }
        }
    }
}
